version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - BeeeQueue
  ignore:
  - dependency-name: anitomyscript
    versions:
    - "> 1.0.2"
  - dependency-name: electron
    versions:
    - ">= 6.a"
    - "< 7"
  - dependency-name: "@types/jest"
    versions:
    - ">= 26.0.a"
    - "< 26.1"
  - dependency-name: "@types/node"
    versions:
    - ">= 11.a"
    - "< 12"
  - dependency-name: "@types/node"
    versions:
    - "> 12.12.44"
