branches:
  only:
    - master

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: '11.15'
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - '$HOME/.cache/electron'
    - '$HOME/.cache/electron-builder'

script:
  - yarn build -p onTagOrDraft -m
