version: 2.1

executors:
  linux:
    docker:
      - image: circleci/node:12
    working_directory: ~/app
  # macos:
  #   macos:
  #     xcode: '9.4'
  #   working_directory: ~/app

jobs:
  checkout_code:
    executor: linux
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./*

  dependencies:
    executor: linux
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install NPM dependencies
          command: yarn install --frozen-lockfile
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  build_linux:
    executor: linux
    docker:
      - image: electronuserland/builder:wine
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn run build -wl --x64 -p onTagOrDraft

  compile:
    executor: linux
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Compile
          command: yarn vue-cli-service build -wl --ia32 --x64

  # build_macos:
  #   executor: macos
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: Run tests
  #         command: yarn run build -m

  lint:
    executor: linux
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run linting
          command: yarn run lint:ci
      - store_test_results:
          when: always
          path: test-results

workflows:
  version: 2
  build_test_lint:
    jobs:
      - checkout_code
      - dependencies:
          requires:
            - checkout_code
      - compile:
          requires:
            - dependencies
      - build_linux:
          requires:
            - compile
      # - build_macos:
      #     requires:
      #       - dependencies
      - lint:
          requires:
            - dependencies
